spring:
  datasource:
    url: jdbc:mysql//localhost:3306/seckill
    username: root
    password: 8799
    driver-class-name: com.mysql.jdbc.Driveral
    dbcp2:
      initial-size: 1
      min-idle: 3
      max-idle: 20
      max-wait-millis: 3000
      min-evictable-idle-time-millis: 60000
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cn.seckill.pojo


